# Generated by Django 5.2.3 on 2025-06-12 17:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=64, verbose_name='Familiyasi')),
                ('position', models.CharField(max_length=128, verbose_name='Lavozimi')),
                ('department', models.CharField(blank=True, max_length=128, null=True, verbose_name="Bo'limi")),
                ('location', models.CharField(choices=[('office', 'Ofis'), ('factory', 'Zavod'), ('remote', 'Masofaviy'), ('field', 'Dala'), ('other', 'Boshqa')], default='office', max_length=20, verbose_name='Joylashuv')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqamini to'g'ri (+998xxxxxxxxx) formatda kiriting.", regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmagan'), ('late', 'Kechikdi'), ('vacation', 'Ta’til'), ('sick', 'Kasal'), ('business', 'Ish safarida'), ('offday', 'Ish kuni emas')], max_length=16, verbose_name='Davomat holati')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh/sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='blog.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
