# Generated by Django 5.2.1 on 2025-07-08 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmagan'), ('late', 'Kechikdi'), ('vacation', "Ta'til"), ('sick', 'Kasal'), ('business', 'Ish safarida'), ('offday', 'Ish kuni emas')], max_length=16, verbose_name='Davomat holati'),
        ),
        migrations.CreateModel(
            name='MonthlyEmployeeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('month', models.PositiveIntegerField(verbose_name='Oy')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mukofot')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jarima')),
                ('days_in_month', models.PositiveIntegerField(default=0, verbose_name='Oy kunlari')),
                ('worked_days', models.PositiveIntegerField(default=0, verbose_name='Ishlangan kunlar')),
                ('accrued', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Hisoblangan')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan")),
                ('debt_start', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Boshlang'ich qarzdorlik")),
                ('debt_end', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oxirgi qarzdorlik')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='blog.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Oylik xodim statistikasi',
                'verbose_name_plural': 'Oylik xodim statistikasi',
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
