# Generated by Django 5.2.1 on 2025-07-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_attendance_created_at_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyemployeestat',
            name='currency',
            field=models.CharField(choices=[('UZS', 'So‘m'), ('USD', 'Dollar'), ('EUR', 'Yevro')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
    ]
