# Generated by Django 5.2.1 on 2025-07-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_monthlyemployeestat_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('full', 'To‘liq stavka'), ('half', '15 kunlik/yarim stavka'), ('office', 'Ofis xodimi (davomatsiz)')], default='full', max_length=10, verbose_name='Xodim turi'),
        ),
        migrations.AddField(
            model_name='monthlyemployeestat',
            name='manual_salary',
            field=models.BooleanField(default=False, verbose_name='Oylik faqat qo‘lda kiritiladi (ofis xodimi)'),
        ),
    ]
