# Generated by Django 5.2.1 on 2025-07-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_employee_employee_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_type",
            field=models.CharField(
                choices=[
                    ("full", "To‘liq stavka"),
                    ("half", "15 kunlik/yarim stavka"),
                    ("office", "Ofis xodimi (davomatsiz)"),
                    ("weekly", "Haftada 1 kun (to‘liq stavka)"),
                    ("guard", "Qorovul (oyda 10 kun)"),
                ],
                default="full",
                max_length=10,
                verbose_name="Xodim turi",
            ),
        ),
    ]
