# Generated by Django 5.2.1 on 2026-03-31 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_employee_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(1, '1-komanda'), (2, '2-komanda'), (3, '3-komanda')], unique=True, verbose_name='Komanda raqami')),
                ('name', models.CharField(max_length=64, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Komanda',
                'verbose_name_plural': 'Komandalar',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('nalivshik', 'Nalivshik'), ('other', 'Boshqa')], default='other', max_length=32, verbose_name='Lavozim turi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='blog.team', verbose_name='Komanda'),
        ),
    ]
