# Generated by Django 5.2.1 on 2026-04-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_team_employee_role_employee_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='NalivshikShiftOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_overrides', to='blog.team', verbose_name='Kunduzgi komanda')),
                ('night_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_overrides', to='blog.team', verbose_name='Tungi komanda')),
            ],
            options={
                'verbose_name': 'Nalivshik smena override',
                'verbose_name_plural': "Nalivshik smena override'lari",
                'ordering': ['-date'],
            },
        ),
    ]
