# Generated by Django 4.2.7 on 2026-07-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_employee_middle_name_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyemployeestat',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shu oy oylikdan ushlab qolingan oldindan qarz summasi.', max_digits=12, verbose_name='Qarzdan ushlab qolish'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('full', 'To‘liq stavka'), ('half', '15 kunlik/smena'), ('office', 'Ofis xodimi (davomatsiz)'), ('weekly', 'Haftada 1 kun (to‘liq stavka)'), ('guard', 'Qorovul (oyda 10 kun)')], default='full', max_length=10, verbose_name='Xodim turi'),
        ),
        migrations.CreateModel(
            name='EmployeeAdvanceLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami qarz')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Qolgan qarz')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oylik ushlab qolish')),
                ('issued_at', models.DateField(verbose_name='Qarz berilgan sana')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('currency', models.CharField(choices=[('UZS', 'So‘m'), ('USD', 'Dollar'), ('EUR', 'Yevro')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_loans', to='blog.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Oldindan qarz',
                'verbose_name_plural': 'Oldindan qarzlar',
                'ordering': ['issued_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ushlab qolish')),
                ('deducted_at', models.DateField(verbose_name='Sana')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='blog.employeeadvanceloan', verbose_name='Qarz')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_deductions', to='blog.monthlyemployeestat', verbose_name='Oylik statistika')),
            ],
            options={
                'verbose_name': 'Qarz ushlab qolish',
                'verbose_name_plural': 'Qarz ushlab qolishlar',
                'ordering': ['deducted_at', 'pk'],
                'unique_together': {('loan', 'stat')},
            },
        ),
    ]
